-- Operator PO lifecycle events (explicit stamps; audit via po_events).

ALTER TYPE "POEventKind" ADD VALUE IF NOT EXISTS 'OPERATOR_VENDOR_ACKNOWLEDGED';
ALTER TYPE "POEventKind" ADD VALUE IF NOT EXISTS 'OPERATOR_BLOCKED';
ALTER TYPE "POEventKind" ADD VALUE IF NOT EXISTS 'OPERATOR_BLOCKED_CLEARED';
ALTER TYPE "POEventKind" ADD VALUE IF NOT EXISTS 'OPERATOR_RECEIVED_COMPLETE';
